import React, { useState } from 'react';
import { Copy, Check, Terminal, ExternalLink, Zap } from 'lucide-react';
import { Reveal } from './Reveal';

interface CodePreviewProps {
  onNavigate: (view: string) => void;
}

export const CodePreview: React.FC<CodePreviewProps> = ({ onNavigate }) => {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'preview' | 'code'>('preview');

  const codeSnippet = `-- Generated by Dalley Web
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local SPR = require(ReplicatedStorage.SPR) -- Spring Physics Module

local Button = script.Parent

-- Spring Configuration
local HOVER_SPRING = {
    Damping = 0.8,
    Frequency = 4,
    Speed = 20
}

Button.MouseEnter:Connect(function()
    -- Apply spring physics for buttery smooth scale
    SPR.target(Button, HOVER_SPRING.Damping, HOVER_SPRING.Frequency, {
        Scale = 1.1,
        Rotation = 5,
        BackgroundColor3 = Color3.fromRGB(236, 72, 153)
    })
end)

Button.MouseLeave:Connect(function()
    SPR.target(Button, HOVER_SPRING.Damping, HOVER_SPRING.Frequency, {
        Scale = 1.0,
        Rotation = 0,
        BackgroundColor3 = Color3.fromRGB(24, 24, 27)
    })
end)`;

  const handleCopy = async () => {
    try {
        await navigator.clipboard.writeText(codeSnippet);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    } catch (err) {
        console.error("Failed to copy", err);
    }
  };

  const handleTryItOut = () => {
    onNavigate('editor');
  };
  
  const highlightCode = (code: string) => {
      // Tokenizer to safely highlight syntax without breaking HTML tags
      const tokens: { id: string; val: string }[] = [];
      const save = (val: string) => {
          const id = `__TOK_${tokens.length}__`;
          tokens.push({ id, val });
          return id;
      };

      return code.split('\n').map((line, i) => {
          let processed = line;

          // 1. Strings (double quotes)
          processed = processed.replace(/"[^"]*"/g, (m) => save(`<span class="text-green-400">${m}</span>`));
          
          // 2. Comments
          processed = processed.replace(/--.*/g, (m) => save(`<span class="text-zinc-500 italic">${m}</span>`));

          // 3. Keywords
          processed = processed.replace(/\b(local|function|end|require|return|if|then|else|do)\b/g, (m) => save(`<span class="text-pink-400 font-bold">${m}</span>`));

          // 4. Globals & Built-ins
          processed = processed.replace(/\b(game|script|workspace|Color3|Vector3|UDim2|Enum)\b/g, (m) => save(`<span class="text-blue-400">${m}</span>`));
          
          // 5. Methods/Properties (approximate: word preceded by . or :)
          // We assume method names start with a letter
          processed = processed.replace(/([.:])([a-zA-Z_]\w*)/g, (match, p1, p2) => {
             return p1 + save(`<span class="text-yellow-300">${p2}</span>`);
          });

          // 6. Numbers
          processed = processed.replace(/\b\d+(\.\d+)?\b/g, (m) => save(`<span class="text-orange-400">${m}</span>`));
          
          // Restore tokens
          // Since tokens were saved sequentially and unique IDs are used, simple replacement works
          tokens.forEach((t) => {
              processed = processed.replace(t.id, t.val);
          });

          return (
              <div key={i} className="table-row">
                  <span className="table-cell select-none text-zinc-800 pr-4 text-right w-8 text-[10px] pt-0.5">{i + 1}</span>
                  <span className="table-cell">
                      <span dangerouslySetInnerHTML={{ __html: processed }} />
                  </span>
              </div>
          );
      });
  };

  return (
    <section id="code-export" className="py-32 relative overflow-hidden bg-black border-y border-white/5">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(236,72,153,0.05),transparent_70%)]"></div>
      
      <div className="max-w-6xl mx-auto px-6 relative z-10">
        <div className="grid md:grid-cols-2 gap-16 items-center">
            
            <div className="order-2 md:order-1">
                <Reveal width="100%" variant="slide-right">
                    <div className="inline-flex items-center gap-2 text-pink-400 mb-6 bg-pink-950/30 px-4 py-1.5 rounded-full border border-pink-900/50">
                        <Zap className="w-4 h-4" />
                        <span className="text-sm font-medium tracking-wide">SPR Motion Engine</span>
                    </div>
                    <h2 className="font-sans text-4xl md:text-5xl font-bold mb-6 text-white tracking-tight">
                        Physics-based <br/>
                        <span className="text-zinc-500">Animation Logic.</span>
                    </h2>
                    <p className="text-zinc-400 text-lg mb-8 leading-relaxed">
                        Dalley writes the complex SPR (Spring) module code for you. No more linear tweens. Create UIs that feel alive, responsive, and professional with zero math required.
                    </p>
                    
                    <div className="flex gap-4">
                       <button 
                         onClick={handleTryItOut}
                         className="px-8 py-3 bg-white text-black font-bold rounded-full hover:bg-pink-500 hover:text-white transition-all hover:scale-105 shadow-[0_0_20px_rgba(255,255,255,0.3)] flex items-center gap-2"
                       >
                         Try it out <ExternalLink className="w-4 h-4" />
                       </button>
                    </div>
                </Reveal>
            </div>

            <div className="order-1 md:order-2">
                <Reveal width="100%" variant="zoom" delay={0.2}>
                    <div className="bg-[#1e1e2e] rounded-xl overflow-hidden shadow-2xl shadow-pink-900/20 border border-white/10 flex flex-col h-[500px]">
                        <div className="flex items-center justify-between px-4 py-3 bg-[#181825] border-b border-white/5">
                            <div className="flex gap-1 bg-black/20 p-1 rounded-lg">
                                <button 
                                    onClick={() => setActiveTab('preview')}
                                    className={`text-xs font-bold px-4 py-1.5 rounded-md transition-all ${activeTab === 'preview' ? 'bg-zinc-700 text-white shadow-sm' : 'text-zinc-500 hover:text-white'}`}
                                >
                                    Example
                                </button>
                                <button 
                                    onClick={() => setActiveTab('code')}
                                    className={`text-xs font-bold px-4 py-1.5 rounded-md transition-all ${activeTab === 'code' ? 'bg-zinc-700 text-white shadow-sm' : 'text-zinc-500 hover:text-white'}`}
                                >
                                    Lua Code
                                </button>
                            </div>
                            {activeTab === 'code' && (
                                <button onClick={handleCopy} className="text-zinc-500 hover:text-white transition-colors flex items-center gap-2 text-xs">
                                    {copied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
                                    {copied ? 'Copied' : 'Copy'}
                                </button>
                            )}
                        </div>
                        
                        <div className="flex-1 relative overflow-hidden">
                            {activeTab === 'preview' ? (
                                <div className="absolute inset-0 bg-[#0f0f14] flex flex-col items-center justify-center p-8 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-100">
                                    <div className="text-zinc-500 text-xs mb-8 uppercase tracking-widest font-mono">Interactive Preview</div>
                                    
                                    <button className="group relative w-64 h-20 rounded-2xl bg-zinc-900 border border-white/10 transition-all duration-300 ease-[cubic-bezier(0.175,0.885,0.32,1.275)] hover:scale-110 hover:rotate-2 hover:bg-pink-600 hover:border-pink-400 hover:shadow-[0_0_30px_rgba(236,72,153,0.4)] flex items-center justify-center gap-3">
                                        <div className="w-8 h-8 rounded-lg bg-white/10 flex items-center justify-center">
                                            <Zap className="w-5 h-5 text-white" />
                                        </div>
                                        <div className="text-left">
                                            <div className="text-white font-bold text-lg">Hover Me</div>
                                            <div className="text-white/50 text-xs">Spring Physics Enabled</div>
                                        </div>
                                    </button>
                                    
                                    <div className="mt-12 text-center">
                                        <p className="text-zinc-600 text-sm max-w-xs mx-auto">
                                            Actual in-game behavior using the generated SPR code. Notice the bounce and rotation.
                                        </p>
                                    </div>
                                </div>
                            ) : (
                                <div className="absolute inset-0 bg-[#0f0f14] p-6 overflow-auto custom-scrollbar">
                                    <pre className="font-mono text-xs md:text-sm leading-relaxed text-zinc-300">
                                        <code>{highlightCode(codeSnippet)}</code>
                                    </pre>
                                </div>
                            )}
                        </div>
                    </div>
                </Reveal>
            </div>
        </div>
      </div>
    </section>
  );
};